[package]
description = "Intersection over two iterator"
license = "GPL-3.0"
name = "intersect_iter"
version = "0.1.0"
authors = ["Jojii Jojii at gmx net"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
